name: DEPLOY
on:
  push:
    branches:
    - build

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: build
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /website/weather
        remote_host: simba-fs.dev
        remote_user: simba
        remote_key: ${{ secrets.DEPLOY_KEY }}
